destination_registries:
  registry.cn-hangzhou.aliyuncs.com:
    username: "晓叶小小叶"
    password: "ykl2000627"
    insecure: true
    type: "ali"
    namespace: "ns-ykl"

image_list: |
  registry.aliyuncs.com/google_containers/kube-apiserver:v1.34.4
  registry.aliyuncs.com/google_containers/kube-controller-manager:v1.34.4
  registry.aliyuncs.com/google_containers/kube-scheduler:v1.34.4
  registry.aliyuncs.com/google_containers/kube-proxy:v1.34.4
  registry.aliyuncs.com/google_containers/coredns:v1.12.1
  registry.aliyuncs.com/google_containers/pause:3.10.1
  registry.aliyuncs.com/google_containers/etcd:3.6.5-0
