# 可选：为不同源仓库配置认证信息，仅私有仓库需要
source_registries:
  registry.example.com:
    username: "your_user"
    password: "your_password"
    insecure: true

destination_registries:
  # 示例 1: 私有 Harbor 仓库
  # ykl.io:40443:
  #   username: "admin"
  #   password: "your_password"
  #   insecure: true
  #   type: "harbor"

  # 示例 2: 阿里云容器镜像服务 (个人版/企业版)
  registry.cn-hangzhou.aliyuncs.com:
    username: "your_aliyun_user"
    password: "your_registry_password"
    type: "ali"
    namespace: "your-ns"

image_list: |
  docker.io/rook/ceph:v1.19.0
  quay.io/cephcsi/cephcsi:v3.16.0
  registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.15.0
  registry.k8s.io/sig-storage/csi-provisioner:v6.0.0
  registry.k8s.io/sig-storage/csi-snapshotter:v8.4.0
  registry.k8s.io/sig-storage/csi-attacher:v4.10.0
  registry.k8s.io/sig-storage/csi-resizer:v2.0.0
  quay.io/csiaddons/k8s-sidecar:v0.14.0
  docker.io/library/nginx #arch=amd64,arm64
